[package]
name = "eip712"
version = "0.1.0"
authors = ["Seun LanLege <seunlanlege@gmail.com>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.79"
serde = "1.0.79"
serde_json = "1.0.28"
quickersort = "3.0.1"
ethabi = "6.0.1"
keccak-hash = "0.1.2"
ethereum-types = "0.4.0"
hex = "0.3.2"

